services:

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - gem_data:/usr/local/bundle
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    stdin_open: true
    tty: true
    env_file:
      - .env

  front:
    build: ./front
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - ./front:/app
    depends_on:
      - api

  db:
    image: mysql:8.4
    ports:
      - 4306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env

volumes:
  mysql-data:
  gem_data: