default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_0900_ai_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: db
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  port: 3306

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_TEST_DATABASE'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
